default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: dpg-d4ctbr1r0fns73aavd9g-a.oregon-postgres.render.com
  port: 5432
  username: drwise_db_user
  password: y9XcRZgTOn6LNoLfb3G5v5uUjxPZAuZz

development:
  <<: *default
  database: drwise_db

test:
  <<: *default
  database: drwise_db_test

production:
  primary:
    <<: *default
    database: drwise_db

  cable:
    <<: *default
    database: drwise_db

  queue:
    <<: *default
    database: drwise_db

  cache:
    <<: *default
    database: drwise_db