default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] || 'railway' %>
  username: <%= ENV['DATABASE_USERNAME'] || 'postgres' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 'hvbFdFNIxQoViVqAGVmVbGeIFMQMhznP' %>
  host: <%= ENV['DATABASE_HOST'] || 'hayabusa.proxy.rlwy.net' %>
  port: <%= ENV['DATABASE_PORT'] || '49021' %>

test:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] || 'railway' %>
  username: <%= ENV['DATABASE_USERNAME'] || 'postgres' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 'hvbFdFNIxQoViVqAGVmVbGeIFMQMhznP' %>
  host: <%= ENV['DATABASE_HOST'] || 'hayabusa.proxy.rlwy.net' %>
  port: <%= ENV['DATABASE_PORT'] || '49021' %>

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] || 'railway' %>
  username: <%= ENV['DATABASE_USERNAME'] || 'postgres' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 'hvbFdFNIxQoViVqAGVmVbGeIFMQMhznP' %>
  host: <%= ENV['DATABASE_HOST'] || 'postgres.railway.internal' %>
  port: <%= ENV['DATABASE_PORT'] || '5432' %>

# SolidCache configuration
cache:
  production:
    <<: *default
    database: <%= ENV['DATABASE_NAME'] || 'railway' %>
    username: <%= ENV['DATABASE_USERNAME'] || 'postgres' %>
    password: <%= ENV['DATABASE_PASSWORD'] || 'hvbFdFNIxQoViVqAGVmVbGeIFMQMhznP' %>
    host: <%= ENV['DATABASE_HOST'] || 'postgres.railway.internal' %>
    port: <%= ENV['DATABASE_PORT'] || '5432' %>

  development:
    <<: *default
    database: <%= ENV['DATABASE_NAME'] || 'railway' %>
    username: <%= ENV['DATABASE_USERNAME'] || 'postgres' %>
    password: <%= ENV['DATABASE_PASSWORD'] || 'hvbFdFNIxQoViVqAGVmVbGeIFMQMhznP' %>
    host: <%= ENV['DATABASE_HOST'] || 'hayabusa.proxy.rlwy.net' %>
    port: <%= ENV['DATABASE_PORT'] || '49021' %>

  test:
    <<: *default
    database: <%= ENV['DATABASE_NAME'] || 'railway' %>
    username: <%= ENV['DATABASE_USERNAME'] || 'postgres' %>
    password: <%= ENV['DATABASE_PASSWORD'] || 'hvbFdFNIxQoViVqAGVmVbGeIFMQMhznP' %>
    host: <%= ENV['DATABASE_HOST'] || 'hayabusa.proxy.rlwy.net' %>
    port: <%= ENV['DATABASE_PORT'] || '49021' %>

# SolidQueue configuration
queue:
  production:
    <<: *default
    database: <%= ENV['DATABASE_NAME'] || 'railway' %>
    username: <%= ENV['DATABASE_USERNAME'] || 'postgres' %>
    password: <%= ENV['DATABASE_PASSWORD'] || 'hvbFdFNIxQoViVqAGVmVbGeIFMQMhznP' %>
    host: <%= ENV['DATABASE_HOST'] || 'postgres.railway.internal' %>
    port: <%= ENV['DATABASE_PORT'] || '5432' %>

  development:
    <<: *default
    database: <%= ENV['DATABASE_NAME'] || 'railway' %>
    username: <%= ENV['DATABASE_USERNAME'] || 'postgres' %>
    password: <%= ENV['DATABASE_PASSWORD'] || 'hvbFdFNIxQoViVqAGVmVbGeIFMQMhznP' %>
    host: <%= ENV['DATABASE_HOST'] || 'hayabusa.proxy.rlwy.net' %>
    port: <%= ENV['DATABASE_PORT'] || '49021' %>

  test:
    <<: *default
    database: <%= ENV['DATABASE_NAME'] || 'railway' %>
    username: <%= ENV['DATABASE_USERNAME'] || 'postgres' %>
    password: <%= ENV['DATABASE_PASSWORD'] || 'hvbFdFNIxQoViVqAGVmVbGeIFMQMhznP' %>
    host: <%= ENV['DATABASE_HOST'] || 'hayabusa.proxy.rlwy.net' %>
    port: <%= ENV['DATABASE_PORT'] || '49021' %>
